
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  non-x-ray SAM template

Resources:

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: poc/statemachine
      RetentionInDays: 14

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: poc/apigw
      RetentionInDays: 14


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AWSXrayFullAccess"
  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "states.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AWSXrayFullAccess"
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
        - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
        - "arn:aws:iam::aws:policy/AWSXrayFullAccess"

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: $context.requestId
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: 'api/api.yaml'
  xray:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-xray-sdk
      Description: Dependencies for the blank sample app.
      ContentUri: aws_xray_sdk/.
      CompatibleRuntimes:
        - python3.7
        - python3.8
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Logging:
        Destinations:
         - CloudWatchLogsLogGroup:
             LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        Level: ALL
      DefinitionUri: statemachine/asl.json
      Role: !GetAtt StateMachineExecutionRole.Arn
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        SelectPairFunctionArn: !GetAtt SelectPair.Arn
        VerifyPairFunctionArn: !GetAtt VerifyPair.Arn
        SavePairFunctionArn: !GetAtt SavePair.Arn
        NotifyPairFunctionArn: !GetAtt NotifyPair.Arn

  SelectPair:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/poc_select_pair/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaExecutionRole.Arn
      Tracing: Active
      Layers:
        - !Ref xray

  VerifyPair:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/poc_verify_pair/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaExecutionRole.Arn
      Tracing: Active
      Layers:
        - !Ref xray

  SavePair:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/poc_save_db/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaExecutionRole.Arn
      Tracing: Active
      Layers:
        - !Ref xray

  NotifyPair:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/poc_notify_pair/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaExecutionRole.Arn
      Tracing: Active
      Layers:
        - !Ref xray











